// lit element
import { customElement } from 'lit/decorators.js';
import { LitElement, TemplateResult, html, CSSResult } from 'lit';

// memberdashboard
import { coreStyle } from '../../styles/core.style';

@customElement('gigachad-boss')
export class GigachadBoss extends LitElement {
  static get styles(): CSSResult[] {
    return [coreStyle];
  }

  // prettier-ignore
  render(): TemplateResult {
    return html`
    <pre>
    <font color="#000000">   </font><font color="#010002"> </font><font color="#000000"> </font><font color="#0D072F"> </font><font color="#361CC6">:</font><font color="#341BBE">:</font><font color="#341BBF">:::</font><font color="#341CBF">:::::::::::::::</font><font color="#341DBF">:</font><font color="#3516BD">.</font><font color="#3039C8">:</font><font color="#1FBCEE">+</font><font color="#1FBAEE">++</font><font color="#1FB7EA">+</font><font color="#21C7FE">*</font><font color="#137292">-</font><font color="#000202"> </font><font color="#000506"> </font><font color="#000202">   </font><font color="#000101"> </font><font color="#000000">     </font>
    <font color="#000000">   </font><font color="#010002"> </font><font color="#000000"> </font><font color="#0D072F"> </font><font color="#361CC6">:</font><font color="#341BBE">:</font><font color="#341BBF">:::</font><font color="#3419BE">:</font><font color="#3515BD">.</font><font color="#3516BD">.............</font><font color="#3517BD">:</font><font color="#360FBB">.</font><font color="#3134C7">:</font><font color="#1FBCEE">+</font><font color="#1FBAEE">++</font><font color="#1FB7EA">+</font><font color="#21C7FF">*</font><font color="#136F8E">-</font><font color="#000000">           </font>
    <font color="#000000">   </font><font color="#010002"> </font><font color="#000000"> </font><font color="#0D072F"> </font><font color="#361CC6">:</font><font color="#341BBE">:</font><font color="#341BBF">::</font><font color="#3419BF">:</font><font color="#3326C2">:</font><font color="#3134C6">:</font><font color="#3132C6">:</font><font color="#3133C6">:::::::::::::</font><font color="#322DC4">:</font><font color="#2E4BCE">-</font><font color="#1FBCEE">+</font><font color="#1FBAEE">++</font><font color="#1FB7EB">+</font><font color="#21C5FC">*</font><font color="#157C9F">-</font><font color="#041B22"> </font><font color="#051E27"> </font><font color="#051C23"> </font><font color="#051B23"> </font><font color="#051D26"> </font><font color="#020A0D"> </font><font color="#000000"> </font><font color="#000001"> </font><font color="#000000">   </font>
    <font color="#020203">   </font><font color="#030205"> </font><font color="#020303"> </font><font color="#0F0931"> </font><font color="#361EC6">:</font><font color="#341DBF">:</font><font color="#341DC0">:</font><font color="#3420C0">:</font><font color="#3612BD">.</font><font color="#2A65D4">-</font><font color="#1DC2EE">+</font><font color="#1FB4EA">+</font><font color="#1FB7EB">+++</font><font color="#21B9ED">+</font><font color="#22BAEE">+++++</font><font color="#1FB9EE">+++++</font><font color="#1FB9ED">+</font><font color="#1FB8EC">+++++</font><font color="#20B9EC">+</font><font color="#21B9EC">++</font><font color="#21B9ED">+</font><font color="#21B7EA">+</font><font color="#23C5FB">*</font><font color="#0D475B">:</font><font color="#000203"> </font><font color="#000507"> </font><font color="#000203">   </font>
    <font color="#000000">     </font><font color="#050026"> </font><font color="#3714C4">.</font><font color="#3513BC">.</font><font color="#3513BD">.</font><font color="#3516BE">.</font><font color="#3707B9">.</font><font color="#2B65D9">-</font><font color="#1DCFFD">*</font><font color="#1FBFF8">+</font><font color="#1FC3F9">+</font><font color="#1FC2F9">+</font><font color="#20C3F9">*</font><font color="#17BBF1">+</font><font color="#13B7ED">+</font><font color="#14B7ED">++++</font><font color="#1EBAEE">+</font><font color="#1FBBEE">+++</font><font color="#1FBAEE">+</font><font color="#1FBCF0">+</font><font color="#1FC2F9">++++</font><font color="#20C3F9">*</font><font color="#1BBEF4">+</font><font color="#14B7EE">+++</font><font color="#14B4EB">+</font><font color="#16C4FE">+</font><font color="#073F52">.</font><font color="#000000">     </font>
    <font color="#343536">:::</font><font color="#343538">:</font><font color="#363636">:</font><font color="#33395B">:</font><font color="#2F42D0">:</font><font color="#2F42CA">::</font><font color="#2F43CA">:</font><font color="#303CCC">:</font><font color="#2768C3">-</font><font color="#1C99BA">=</font><font color="#1E91BB">=</font><font color="#1E93BB">=</font><font color="#1E94BC">=</font><font color="#1B90B8">=</font><font color="#44B9E1">*</font><font color="#56CBF2">*</font><font color="#55CAF1">*</font><font color="#55CAF2">*</font><font color="#56CAF2">*</font><font color="#54CAF2">*</font><font color="#25BCEE">+</font><font color="#1EB9EE">+</font><font color="#1FBAEE">+</font><font color="#1FB9ED">+</font><font color="#1FBBF0">+</font><font color="#1FB3E5">+</font><font color="#1E93BB">===</font><font color="#1F94BC">=</font><font color="#1A90B7">=</font><font color="#34A9D0">+</font><font color="#56CBF2">*</font><font color="#55CAF1">*</font><font color="#55CAF2">*</font><font color="#55C8EF">*</font><font color="#58D4FD">#</font><font color="#25687F">-</font><font color="#042B39">.</font><font color="#08303D">.</font><font color="#082D3A">...</font>
    <font color="#DCE4E8">%%%</font><font color="#DAE4E8">%</font><font color="#E5E6E7">@</font><font color="#AEDBEA">%</font><font color="#18BFF0">+</font><font color="#1FC0F0">+</font><font color="#1EC0F0">+</font><font color="#1EBDED">+</font><font color="#1ECBFF">*</font><font color="#1E728C">-</font><font color="#1D0D08"> </font><font color="#1D1C1B">.</font><font color="#1D1918">.</font><font color="#201C1B">.</font><font color="#110C0B"> </font><font color="#BFBAB8">#</font><font color="#FFFFFF">@</font><font color="#FFFEFD">@</font><font color="#FFFFFF">@@@</font><font color="#3AC2F0">*</font><font color="#19B8EE">+</font><font color="#20BAEE">+</font><font color="#1FB9EC">+</font><font color="#1FC0F7">+</font><font color="#1F9DC7">=</font><font color="#1D1716"> </font><font color="#1D1918">..</font><font color="#211C1B">.</font><font color="#0D0808"> </font><font color="#797573">=</font><font color="#FFFFFF">@</font><font color="#FFFEFD">@</font><font color="#FFFFFF">@@@</font><font color="#78D9FA">#</font><font color="#11BBF5">+</font><font color="#23C2F6">+</font><font color="#20C1F7">+++</font>
    <font color="#D2DADE">%%%</font><font color="#D0DADE">%</font><font color="#DBDCDD">%</font><font color="#A7D3E2">#</font><font color="#19B8EF">+</font><font color="#20B9EE">+</font><font color="#1FB9EE">+</font><font color="#1FB6EA">+</font><font color="#20C5FE">*</font><font color="#166987">-</font><font color="#0B0200"> </font><font color="#0B1112"> </font><font color="#0B0D0F"> </font><font color="#0E1112"> </font><font color="#000102"> </font><font color="#B2B4B5">#</font><font color="#FDFEFF">@</font><font color="#FAFBFC">@</font><font color="#FCFFFF">@</font><font color="#FDFEFF">@</font><font color="#F6FDFE">@</font><font color="#39C2F0">*</font><font color="#19B8EE">+</font><font color="#20BAEE">+</font><font color="#1FB9EC">+</font><font color="#20C1F8">+</font><font color="#1B9AC6">=</font><font color="#0B0B0D"> </font><font color="#0B0D0F">  </font><font color="#0F1112"> </font><font color="#000000"> </font><font color="#6A6D6D">=</font><font color="#FDFEFF">@</font><font color="#FAFBFC">@</font><font color="#FDFFFF">@</font><font color="#FAFDFF">@</font><font color="#FDFFFF">@</font><font color="#73D3F3">#</font><font color="#10B4EB">+</font><font color="#22BAEC">+</font><font color="#1FB9EC">+++</font>
    <font color="#D4DCE0">%%%</font><font color="#D2DCE0">%</font><font color="#DDDEDF">%</font><font color="#A8D4E3">#</font><font color="#19B9EF">+</font><font color="#20BAEE">+</font><font color="#1FBAEE">+</font><font color="#20B8EC">+</font><font color="#19BFF7">+</font><font color="#4295B2">=</font><font color="#6B6462">=</font><font color="#696C6E">=</font><font color="#6A6B6C">=</font><font color="#6C6D6D">=</font><font color="#626364">-</font><font color="#D1D1D2">%</font><font color="#FFFFFF">@</font><font color="#FDFDFD">@</font><font color="#FEFFFF">@</font><font color="#FFFFFF">@</font><font color="#F8FDFE">@</font><font color="#39C2F0">*</font><font color="#19B8EE">+</font><font color="#20BAEE">+</font><font color="#20BAED">+</font><font color="#1CBDF3">+</font><font color="#2DACD6">+</font><font color="#6A6A6A">=</font><font color="#6A6B6C">==</font><font color="#6D6D6E">=</font><font color="#606062">-</font><font color="#A5A5A5">*</font><font color="#FFFFFF">@</font><font color="#FDFDFD">@</font><font color="#FFFFFF">@</font><font color="#FCFEFF">@</font><font color="#FFFFFF">@</font><font color="#74D4F4">#</font><font color="#10B5ED">+</font><font color="#22BBEE">+</font><font color="#1FBAEE">+++</font>
    <font color="#D4DCE0">%%%</font><font color="#D2DCE0">%</font><font color="#DDDEDF">%</font><font color="#A8D4E3">#</font><font color="#19B9EF">+</font><font color="#20BAEE">+</font><font color="#1FBAEE">+</font><font color="#23BBEE">+</font><font color="#0EB4EC">+</font><font color="#8CE0FC">#</font><font color="#FFFFFF">@@@@@@</font><font color="#FBFEFF">@</font><font color="#FCFEFF">@</font><font color="#FAFEFF">@</font><font color="#FBFEFF">@</font><font color="#F4FCFE">@</font><font color="#39C2F0">*</font><font color="#19B8EE">+</font><font color="#20BAEE">+</font><font color="#21BBEE">+</font><font color="#16B7EC">+</font><font color="#4AC9F3">*</font><font color="#FFFFFF">@@@@@@</font><font color="#FBFEFF">@</font><font color="#FCFEFF">@</font><font color="#FBFEFF">@</font><font color="#F8FDFF">@</font><font color="#FBFEFF">@</font><font color="#74D3F3">#</font><font color="#12B4EC">+</font><font color="#24BAED">+</font><font color="#21B9ED">+++</font>
    <font color="#D4DCE0">%%%</font><font color="#D2DCE0">%</font><font color="#DDDEDF">%</font><font color="#A8D4E3">#</font><font color="#19B9EF">+</font><font color="#20BAEE">+</font><font color="#1FBAEE">+</font><font color="#23BBEE">+</font><font color="#0EB5ED">+</font><font color="#8DDBF5">#</font><font color="#FFFFFD">@@@@@</font><font color="#FFFFFF">@@@@@@</font><font color="#3BC3F0">*</font><font color="#19B8EE">+</font><font color="#20BAEE">+</font><font color="#21BBEE">+</font><font color="#15B7ED">+</font><font color="#4AC7F1">*</font><font color="#FFFFFD">@@@@@</font><font color="#FFFFFE">@</font><font color="#FFFFFF">@@@@@</font><font color="#75DAF8">#</font><font color="#06BBF3">+</font><font color="#1AC1F4">+</font><font color="#17C0F4">+++</font>
    <font color="#D4DCE0">%%%</font><font color="#D2DCE0">%</font><font color="#DDDEDF">%</font><font color="#A8D4E3">#</font><font color="#19B9EF">+</font><font color="#20BAEE">+</font><font color="#1FBAEE">+</font><font color="#21BBEE">+</font><font color="#16B7ED">+</font><font color="#57CBF2">*</font><font color="#98DFF7">%</font><font color="#95DEF7">#</font><font color="#97DFF7">%%%%%%%%</font><font color="#93DEF7">#</font><font color="#2DBEEF">+</font><font color="#1CB9EE">+</font><font color="#20BAEE">+</font><font color="#20BBEE">+</font><font color="#1AB8ED">+</font><font color="#35C1F0">*</font><font color="#97DFF7">%%%%%%%%%</font><font color="#96DEF7">%</font><font color="#95E2FA">%</font><font color="#6DB0D9">*</font><font color="#4E8EC4">+</font><font color="#5494C7">+</font><font color="#5393C7">+++</font>
    <font color="#D1D9DF">%%%</font><font color="#D0D9DF">%</font><font color="#DADBDE">%</font><font color="#A6D2E3">#</font><font color="#19B9EF">+</font><font color="#20BAEE">+</font><font color="#1FBAEE">++</font><font color="#20BAEE">+</font><font color="#17B8ED">+</font><font color="#0FB5ED">+++++</font><font color="#11B6ED">+</font><font color="#12B6ED">++++</font><font color="#13B6ED">+</font><font color="#21BBEE">+</font><font color="#23BBEE">+</font><font color="#22BBEE">++</font><font color="#23BBEE">+</font><font color="#20BAEE">+</font><font color="#12B6ED">+++++</font><font color="#11B6ED">+</font><font color="#0FB5ED">+++</font><font color="#11B4EC">+</font><font color="#07BAF2">+</font><font color="#6480B6">=</font><font color="#A05B8E">=</font><font color="#956295">=</font><font color="#976194">===</font>
    <font color="#DFE9E2">@@@</font><font color="#DDE9E2">%</font><font color="#E9ECE1">@</font><font color="#B0DEE5">%</font><font color="#19B9EF">+</font><font color="#20BAEE">+</font><font color="#1FBAEE">+++</font><font color="#21BBEE">+</font><font color="#23BBEE">+++</font><font color="#22BBEE">+</font><font color="#24BBEE">+</font><font color="#18B8ED">+</font><font color="#13B6ED">+++++</font><font color="#10B5ED">+</font><font color="#0FB5ED">++++</font><font color="#10B5ED">+</font><font color="#13B6ED">+++++</font><font color="#19B8EE">+</font><font color="#24BBEE">+</font><font color="#22BBEE">+</font><font color="#23BBEE">+</font><font color="#25BAED">+</font><font color="#1CC0F3">+</font><font color="#6587BB">+</font><font color="#946295">=</font><font color="#8B699C">=</font><font color="#8D689B">===</font>
    <font color="#776CCD">===</font><font color="#766DCD">=</font><font color="#7C68CB">=</font><font color="#627FD5">+</font><font color="#1CBDF0">+</font><font color="#1FB9EE">+</font><font color="#1FBAEE">+++++++</font><font color="#21BBEE">+</font><font color="#18B8ED">+</font><font color="#79D6F5">#</font><font color="#A2E2F8">%</font><font color="#9FE1F8">%</font><font color="#A1E2F8">%%%%%%%%%%%%</font><font color="#9FE1F8">%</font><font color="#A2E2F8">%</font><font color="#6ED2F4">#</font><font color="#16B7ED">+</font><font color="#21BBEE">+</font><font color="#1FBAEE">+</font><font color="#21B9ED">+</font><font color="#18BFF3">+</font><font color="#6586BA">+</font><font color="#966194">=</font><font color="#8D689B">=</font><font color="#8F679A">===</font>
    <font color="#280DBA">...</font><font color="#280FBC">.</font><font color="#2904B8">.</font><font color="#2637C6">:</font><font color="#1FBFF0">+</font><font color="#1FB7ED">+</font><font color="#1FB8ED">+++</font><font color="#1FB9EE">+</font><font color="#1FBAEE">+++</font><font color="#22BBEE">+</font><font color="#12B6ED">+</font><font color="#C3EDFB">%</font><font color="#FFFFFF">@@@@@@@@@@@@@@@@</font><font color="#AFE6F9">%</font><font color="#0FB5ED">+</font><font color="#22BBEE">+</font><font color="#1FBAEE">+</font><font color="#21B9ED">+</font><font color="#18BFF3">+</font><font color="#6485B9">+</font><font color="#946092">=</font><font color="#8B6799">=</font><font color="#8D6698">===</font>
    <font color="#3920CA">:::</font><font color="#3922CB">:</font><font color="#3B17C8">:</font><font color="#3348D3">-</font><font color="#1DC9F2">*</font><font color="#1EC2F1">+</font><font color="#1EC3F1">+</font><font color="#1EC2F0">+</font><font color="#1EC3F1">+</font><font color="#1EBFEF">+</font><font color="#1FB9EE">+</font><font color="#1FBAEE">++</font><font color="#22BBEE">+</font><font color="#13B6ED">+</font><font color="#C0ECFA">%</font><font color="#FFFFFF">@@@@@@@@@@@@@@@@</font><font color="#ACE6F8">%</font><font color="#0FB5ED">+</font><font color="#22BBEE">+</font><font color="#1FBAEE">+</font><font color="#21B9ED">+</font><font color="#18BFF2">+</font><font color="#6A89BF">+</font><font color="#9E669C">=</font><font color="#956DA3">=</font><font color="#976DA2">+++</font>
    <font color="#10083B">   </font><font color="#11093D"> </font><font color="#10063A"> </font><font color="#17195F">.</font><font color="#2F4ED3">-</font><font color="#2E4CCD">--</font><font color="#2E4ECE">-</font><font color="#2F44CB">-</font><font color="#277FDD">=</font><font color="#1EC2F0">+</font><font color="#1FB8ED">+</font><font color="#1FBAEE">+</font><font color="#20BAEE">+</font><font color="#1BB9EE">+</font><font color="#4FC9F1">*</font><font color="#65CFF3">#</font><font color="#63CFF3">#</font><font color="#64CFF3">############</font><font color="#63CFF3">#</font><font color="#65D0F3">#</font><font color="#49C7F1">*</font><font color="#1AB9EE">+</font><font color="#20BAEE">+</font><font color="#1FBAEE">+</font><font color="#20B8EC">+</font><font color="#1EC4FA">*</font><font color="#275A78">-</font><font color="#2E1D2D">.</font><font color="#2C2233">.</font><font color="#2C202F">...</font>
    <font color="#000000">     </font><font color="#0B0326"> </font><font color="#3712C3">.</font><font color="#3512BB">.</font><font color="#3511BC">.</font><font color="#3515BD">.</font><font color="#3706B9">.</font><font color="#2B60D4">-</font><font color="#1DC6F1">+</font><font color="#1FB7ED">+</font><font color="#1FBAEE">++</font><font color="#20BAEE">+</font><font color="#16B7ED">+</font><font color="#11B5EC">+</font><font color="#12B5EC">+</font><font color="#11B5EC">+++++++++</font><font color="#12B6ED">++++</font><font color="#11B6ED">+</font><font color="#17B7ED">+</font><font color="#20BAEE">+</font><font color="#1FBAEE">++</font><font color="#1FB7EB">+</font><font color="#22C6FE">*</font><font color="#074254">.</font><font color="#000000">     </font>
    <font color="#010003">   </font><font color="#020005"> </font><font color="#010003"> </font><font color="#0D0831"> </font><font color="#361EC7">:</font><font color="#341DBF">:</font><font color="#341DC0">:</font><font color="#3420C1">:</font><font color="#3612BD">.</font><font color="#2A66D5">-</font><font color="#1DC5F1">+</font><font color="#1FB7ED">+</font><font color="#1FBAEE">+++</font><font color="#22BDF2">+</font><font color="#23BFF3">++++++++++</font><font color="#23BEF2">+</font><font color="#22BBEE">+++++</font><font color="#21BBEE">+</font><font color="#1FBAEE">+++</font><font color="#1FB7EB">+</font><font color="#21C6FD">*</font><font color="#0D475B">:</font><font color="#020102"> </font><font color="#020406"> </font><font color="#020102">   </font>
    <font color="#000000">   </font><font color="#010002"> </font><font color="#000000"> </font><font color="#0D072F"> </font><font color="#361CC6">:</font><font color="#341BBE">:</font><font color="#341BBF">:</font><font color="#341EC0">:</font><font color="#3610BC">.</font><font color="#2A65D5">-</font><font color="#1DC5F1">+</font><font color="#1FB7ED">+</font><font color="#1FBAEE">+</font><font color="#1FB8EC">+</font><font color="#21C2F8">+</font><font color="#0E546C">:</font><font color="#062630">.</font><font color="#062833">.</font><font color="#062631">......</font><font color="#062833">.</font><font color="#062630">.</font><font color="#0B4154">:</font><font color="#1FBCF0">+</font><font color="#1FBAEE">++++++++</font><font color="#1FB7EB">+</font><font color="#21C6FD">*</font><font color="#0C465A">:</font><font color="#000000"> </font><font color="#000304"> </font><font color="#000000">   </font>
    <font color="#000000">   </font><font color="#010002"> </font><font color="#000000"> </font><font color="#0D072F"> </font><font color="#361CC6">:</font><font color="#341BBE">:</font><font color="#341BBF">:</font><font color="#341EC0">:</font><font color="#3610BC">.</font><font color="#2A65D5">-</font><font color="#1DC5F1">+</font><font color="#1FB7ED">+</font><font color="#1FBAEE">+</font><font color="#1FB8EB">+</font><font color="#21C4FC">*</font><font color="#093343">.</font><font color="#000000">          </font><font color="#051B23"> </font><font color="#1FBCF0">+</font><font color="#1FBAEE">++++++++</font><font color="#1FB7EB">+</font><font color="#21C6FD">*</font><font color="#0C465A">:</font><font color="#000000"> </font><font color="#000304"> </font><font color="#000000">   </font>
    <font color="#000000"> </font><font color="#010002"> </font><font color="#000000"> </font><font color="#0D072F"> </font><font color="#361CC6">:</font><font color="#341BBE">:</font><font color="#341BBF">:</font><font color="#341EC0">:</font><font color="#3610BC">.</font><font color="#2A65D5">-</font><font color="#1DC5F1">+</font><font color="#1FB7ED">+</font><font color="#1FBAEE">+</font><font color="#1FB8EB">+</font><font color="#21C4FB">*</font><font color="#0A3A4C">.</font><font color="#000203"> </font><font color="#000406"> </font><font color="#000203">      </font><font color="#000405"> </font><font color="#000203"> </font><font color="#06242E">.</font><font color="#1FBCF0">+</font><font color="#1FBAEE">++++++++</font><font color="#1FB7EB">+</font><font color="#21C6FD">*</font><font color="#0C465A">:</font><font color="#000000"> </font><font color="#000304"> </font><font color="#000000"> </font>
    </pre>
    `;
  }
}
